server:
    port: 7777

spring:
    datasource:
        url: jdbc:mysql://localhost/foodtruck
        username: seulgi
        password: dkdlxl123
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        open-in-view: false
